# Generated by Django 4.1.4 on 2022-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('pesan', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'havindb',
            },
        ),
    ]
